from flask import Blueprint, render_template, request, url_for

# main blueprint
main = Blueprint('main', __name__)

@main.route('/', methods=['GET', 'POST'])
def home_page():
    if request.method == 'GET':
        return render_template('index.html')

    if request.method == 'POST':
        return render_template('story.html')

@main.route('/examples')
def examples():
    """Renders the page that contains examples of
    stories generated by the character model."""
    return render_template('examples.html')